/*
* Open source copyright declaration based on BSD open source template:
* http://www.opensource.org/licenses/bsd-license.php
*
* This file is part of the OPS distribution.
*
* Copyright (c) 2013, Mike Giles and others. Please see the AUTHORS file in
* the main source directory for a full list of copyright holders.
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or without
* modification, are permitted provided that the following conditions are met:
* Redistributions of source code must retain the above copyright
* notice, this list of conditions and the following disclaimer.
* Redistributions in binary form must reproduce the above copyright
* notice, this list of conditions and the following disclaimer in the
* documentation and/or other materials provided with the distribution.
* The name of Mike Giles may not be used to endorse or promote products
* derived from this software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY Mike Giles ''AS IS'' AND ANY
* EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
* WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
* DISCLAIMED. IN NO EVENT SHALL Mike Giles BE LIABLE FOR ANY
* DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
* ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
* (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
* SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/** @brief  Random distributions within OPS
  * @author Valantis Tsinginos
  * @details Declerations of random distributions */

#ifndef __OPS_DISTRIBUTIONS_H
#define __OPS_DISTRIBUTIONS_H

#include <random>
#include "ops_util.h"
#include "ops_exceptions.h"
#include <stdlib.h>

inline char *copy_string(char const *src) {
  const size_t len = strlen(src) + 1;
  char *dest = (char *)xmalloc(sizeof(char) * len);
  snprintf(dest, len, "%s", src);
  return dest;
}


/**
 * Definition of distribution functions for population of
 * ops_dat structures with random values
 */
template <template <typename> class Distribution, typename T>
struct OPSDistribution
{
  Distribution<T> *distribution;  /**< Array of random number functions */
  int dims;  /**< Number of random number functions */
  T *limits;   /**  <Limits of the distribution function - if necessary */
};


/**
 * This routine declaires random distribution numbers generators for
 * two-parameter generator functions with user defined limits
 *
 * @dim    Dimension of the Distribution functions
 * @param  Array containing the parameters of each component of a two
 *         parameter distribution function
 * @param  Minimum and maximum values generated by the distribution
 *         function for each dof.
 *
 * @return a pointer to an OPSDistribution<Distribution, T> object
 */

template<template<typename> class Distribution, typename T>
OPSDistribution<Distribution, T>* ops_declaire_distribution(int dim, T* params, T* limits) {

  OPSDistribution<Distribution, T> *distrib =(OPSDistribution<Distribution, T> *) xmalloc(
                                              sizeof(OPSDistribution<Distribution, T>) * dim); //TODO

  printf("I entered herein to declaire distrib\n");

  distrib->dims = dim;
  distrib->distribution = (Distribution<T> *) xmalloc(sizeof(Distribution<T>) * dim);
  distrib->limits = (T *) xmalloc(sizeof(T) * 2* dim);

  for (int i = 0; i < dim; i++) {
    Distribution<T> create(params[2 * i], params[2 * i + 1]);
    distrib->distribution[i] = create;

    if (limits[2 * i] > limits[2 * i + 1])
      throw OPSException(OPS_INVALID_ARGUMENT, "Error: Upper limit smaller than lower limit");
    distrib->limits[2 * i] = limits[2 * i];
    distrib->limits[2 * i + 1] = limits[2 * i + 1];
  }

  //set limits

  return distrib;
}

/**
 * This routine declaires random distribution numbers generators for
 * two-parameter generator functions without  user defined limits
 *
 * @dim    Dimension of the Distribution functions
 * @param  Array containing the parameters of each component of a two
 *         parameter distribution function
 *
 * @return a pointer to an OPSDistribution<Distribution, T> object
 */

template<template<typename> class Distribution, typename T>
OPSDistribution<Distribution, T>* ops_declaire_distribution(int dim, T* params) {

  OPSDistribution<Distribution, T> *distrib =(OPSDistribution<Distribution, T> *) xmalloc(
                                              sizeof(OPSDistribution<Distribution, T>) * dim); //TODO


  distrib->dims = dim;
  distrib->distribution = (Distribution<T> *) xmalloc(sizeof(Distribution<T>) * dim);
  distrib->limits = (T *) xmalloc(sizeof(T) * 2* dim);

  for (int i = 0; i < dim; i++) {
    Distribution<T> create(params[2 * i], params[2 * i + 1]);
    distrib->distribution[i] = create;

    distrib->limits[2 * i] = distrib->distribution[i].min();
    distrib->limits[2 * i + 1] = distrib->distribution[i].max();
  }

  //set limits

  return distrib;
}

/**
 * This routine declaires random distribution numbers generators for
 * a single-parameter random generator functions with user defined limits
 *
 * @dim    Dimension of the Distribution functions
 * @param  Array containing the parameters of each component of a two
 *         parameter distribution function
 * @param  Minimum and maximum values generated by the distribution
 *         function for each dof.
 *
 * @return a pointer to an OPSDistribution<Distribution, T> object
 */

template<template<typename> class Distribution, typename T>
OPSDistribution<Distribution, T*> ops_declaire_1P_distribution(int dim, T* params, T* limits) {


  OPSDistribution<Distribution, T> *dis =(OPSDistribution<Distribution, T> *) xmalloc(
                                              sizeof(OPSDistribution<Distribution, T>) * dim); //TODO


  dis->dims = dim;
  dis->distri = (Distribution<T> *) xmalloc(sizeof(Distribution<T>) * dim);
  dis->limits = (T *) xmalloc(sizeof(T) * 2* dim);

  for (int i = 0; i < dim; i++) {
    Distribution<T> create(params[2 * i]);
    dis->distribution[i] = create;

    if (limits[2 * i] > limits[2 * i + 1])
      throw OPSException(OPS_INVALID_ARGUMENT, "Error: Upper limit smaller than lower limit");

    dis->limits[2 * i] = limits[2 * i];
    dis->limits[2 * i + 1] = limits[2 * i + 1];
  }

  //set limits

  return dis;
}

/**
 * This routine declaires random distribution numbers generators for
 * a single-parameter random generator functions without
 * user defined limits
 *
 * @dim    Dimension of the Distribution functions
 * @param  Array containing the parameters of each component of a two
 *         parameter distribution function
 *
 * @return a pointer to an OPSDistribution<Distribution, T> object
 */

template<template<typename> class Distribution, typename T>
OPSDistribution<Distribution, T*> ops_declaire_1P_distribution(int dim, T* params) {


  OPSDistribution<Distribution, T> *distrib =(OPSDistribution<Distribution, T> *) xmalloc(
                                              sizeof(OPSDistribution<Distribution, T>) * dim); //TODO


  distrib->dims = dim;
  distrib->distrib = (Distribution<T> *) xmalloc(sizeof(Distribution<T>) * dim);
  distrib->limits = (T *) xmalloc(sizeof(T) * 2* dim);

  for (int i = 0; i < dim; i++) {
    Distribution<T> create(params[2 * i]);
    distrib->distrib[i] = create;

    distrib->limits[2 * i] = distrib->distrib[i].min();
    distrib->limits[2 * i + 1] = distrib->distrib[i].max();
  }

  //set limits

  return distrib;
}

/**
 * This routine produces a random point of size(dim) within the limits of the OPSDistribution
 * object
 *
 * @param Generator              Type of random number engine of the C++ standard library
 * @param OPSDistribution        Pointer to an OPSDistribution function
 * @param gen                    Random number engine
 * @param random                 Generated random point of dimension dim
 */

template<template<typename> class Distribution, typename T, typename Generator>
void ops_generate_random_point(OPSDistribution<Distribution, T> *dist_gen,
                              Generator &gen, T* random) {

  for (int i = 0; i < dist_gen->dims; i++) {
    int a1 = 0;
    T local;
    int iter = 0;
    while (a1 == 0) {
      local = dist_gen->distribution[i](gen);
      if (local >= dist_gen->limits[2 * i] && local <= dist_gen->limits[2 * i + 1])
        a1 = 1;
      iter++;
      if (iter > 100) break;
    }
    random[i] =  local;
  }
}


template<template<typename> class Distribution, typename T>
OPSDistribution<Distribution, T>* ops_free_distribution(OPSDistribution<Distribution, T>*  distri) {
  if (distri == NULL)
    return NULL;

  free(distri->limits);
  free(distri->distribution);

  free(distri);

  return NULL;
}

#endif /* OPS_C_INCLUDE_OPS_DISTRIBUTIONS_H_ */
